name: Sync document vers Dropbox

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Envoyer document.txt vers Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ secrets.DROPBOX_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\": \"/GIT-TEST/document.txt\", \"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @document.txt
